writF:
	latex writing.tex
	bibtex writing.aux
	latex writing.tex
	dvips writing.dvi
	ps2pdf writing.ps
	rm -f writing.aux
	rm -f writing.dvi
	rm -f writing.log
	rm -f writing.ps
	rm -f writing.blg
	rm -f writing.bbl
	rm -f writing.toc